config/routes.rb
Rails.application.routes.draw do
  get 'movie/:imdb' => 'movie#index'
  resources :users
  root 'front_page#index', as: 'front_page_index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, :email, :password_digest, presence: true
  validates :username, :email, uniqueness: true
  validates_length_of :password_digest, :minimum => 8
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/front_page_controller.rb
class FrontPageController < ApplicationController
  def index
  end
end

app/controllers/movie_controller.rb
class MovieController < ApplicationController
  require 'http'
  def index
    imdb = params[:imdb]
    response = HTTP.get('http://www.omdbapi.com/', :params => {i: imdb, plot: 'full'})
    @Movie = JSON.parse(response)
  end
end

app/controllers/nav_controller.rb
class NavController < ApplicationController
  #def _nav
 # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front_page_helper.rb
module FrontPageHelper
end

app/helpers/movie_helper.rb
module MovieHelper
end

app/helpers/nav_helper.rb
module NavHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/front_page/index.html.erb
<h1 class="center-align">Ruby movie database</h1>
<p><%= link_to 'User list', users_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exam</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'nav/nav' %>
    <div class="container">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/movie/_details.html.erb
<div id="movie" class="row">
  <div class="col s12">
    <h1 class="title center-align"><%= @Movie["Title"] %></h1>
    <div class="col m6">
      <img class="right" src="<%= @Movie["Poster"] %>" alt="">
    </div>
    <div class="col m6">
      <p><i class="material-icons yellow-text">star_rate</i><%= @Movie['imdbRating'] %>/10</p>
      <p><%= @Movie['Plot'] %></p>
    </div>
  </div>
</div>

app/views/movie/index.html.erb
<%= render 'details' %>

app/views/nav/_nav.html.erb
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper">
      <div id="brand">
        <%= link_to front_page_index_path, :class => 'brand-logo' do %>
            <i class="material-icons md-36">movie</i>RMDB
        <% end %>
      </div>
      <div id="search-form" style="display: none;">
        <form>
          <div class="input-field">
            <input id="search" type="search" autocomplete="off">
            <label class="label-icon" for="search"><i class="material-icons">search</i></label>
            <i class="material-icons">close</i>
          </div>
        </form>
      </div>
      <ul id="menu" class="right">
        <li id="toggle-search"><a href="#"><i class="material-icons">search</i></a></li>
        <li><%= link_to 'Login', users_path %></li>
      </ul>
    </div>
  </nav>
</div>

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <pre><%= user.errors.inspect %></pre>
      <% user.errors.each do |error| %>
        <li><%= error %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field input-field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>

  <div class="field input-field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field input-field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field input-field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit nil, :class => 'waves-effect waves-light btn' %>
    <%= link_to "Cancel", users_path %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="center-align">Users</h1>

<table class="bordered">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', front_page_index_path %> |
<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1 class="center-align">Register</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>